### ISSUE TITLE
[backend] Return timestamp of last status update

### ISSUE THREAD

**Issue by pfortuna** [Tech4covid19/trackovid19-backend#120]
In requests to /api/v1/user

We need to remove the "cases" property entirely.

And we need to add a new property called "last_status" with the following format:

"last_status": {
        "timestamp": "2020-03-26T20:40:47.000Z",
        "unix_ts": "1585255247824"
}

**Comment by fernanri** [comment]
I propose to change the data model by having the users table reference the last status update entry (the most recent entry in the history table). 

This field can be updated every time a new status update is received.

This will make it easy to return that info without having to search for the most recent entry every time, but instead of retrieving the information as described here, I would suggest to return. the whole case entity (without the symptoms part). Something like:

`"last_status": {
            "postalcode": "4200-192",
            "confinement_state": 4,
            "postalcode1": "4200",
            "postalcode2": "192",
            "status": 3,  
            "latitude": "0",
            "longitude": "0",
            "timestamp": "2020-03-28T00:38:56.000Z",
            "unix_ts": "1585355936874"
        }`

**Comment by pfortuna** [comment]
This is an excellent suggestion. I'll create a specific issue for this.

**Comment by pfortuna** [comment]
I changed my mind. We can do this in a single issue.

- Add a new column "last_status_id" to the DB table "users".
- This column will be a FK linking to the "history" table through "history.id""
- Change /api/v1/users to return this property
"last_status": { "postalcode": "4200-192", "confinement_state": 4, "postalcode1": "4200", "postalcode2": "192", "status": 3, "latitude": "0", "longitude": "0", "timestamp": "2020-03-28T00:38:56.000Z", "unix_ts": "1585355936874" }
- Remove the property "cases" in the same endpoint

Does this look good to you @fernanri ?

**Comment by fernanri** [comment]
That's perfect, @pfortuna!
